apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 2 # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image:  132578005405.dkr.ecr.us-east-1.amazonaws.comtest1:26
        ports:
        - containerPort: 3000  # Port your application listens on
